### ISSUE TITLE
Hide Show Togle not working

### ISSUE THREAD

**Issue by harneyphoto** [Tom-Hirschberger/MMM-TouchButton#1]
Tom. Just back from work and getting back into implementing your module. Shutdown and boot work fine but cant seem to toggle any of the modules.

As this is the screen of my server in my room, I want to toggle all but the clock an night to keep the light down. Ive tried single modules but nothing seems to work. I made the Refresh button the toggle button and still doesnt work.

Im new to this coding so dont understand everything yet. Have attached a copy of my config and screen

Hope you can help

John
[config.txt](https://github.com/Tom-Hirschberger/MMM-TouchButton/files/5925274/config.txt)
![screen](https://user-images.githubusercontent.com/59463330/106883916-9a927700-671b-11eb-8c5b-cce8bf678c07.jpeg)

**Comment by Tom-Hirschberger** [comment]
Hi,

sorry for the misleading example. My module only sends an notification if you press the button. To hide/show modules you need a module like MMM-ModuleToggle which does the work. If you install this module, too it will work out of the box.

**Comment by harneyphoto** [comment]
Cool, thanks for that. Will get onto it

Cheers again

**Comment by harneyphoto** [comment]
Perfect.
