### ISSUE TITLE
Buttons are undefined

### ISSUE THREAD

**Issue by Entropy159** [Tom-Hirschberger/MMM-TouchButton#11]
I set up a button just like the description said, but it shows up as undefined.

**Comment by Entropy159** [comment]
I fixed it, but you should probably mention that the button names can't have a space in them. That threw me off for a moment.

**Comment by Tom-Hirschberger** [comment]
Hi and great to hear you could fix the problem by your self.

There is a hint about the space in the README already in the Buttons->name Option description. But i will add a more conspicuous position.
