### ISSUE TITLE
command and args

### ISSUE THREAD

**Issue by Fabaude** [Tom-Hirschberger/MMM-TouchButton#3]
Hello,
this module looks easy and I like it, I manage to adjust the colors, locations and dimensions. I would like to order a light by http request.
command: "curl"
args: "http: //xxx.xxx.x.xx: xxxx / json.htm? type = command & param = switchlight & idx = xx & switchcmd = On"
But (I'm a beginner) it doesn't work.
In command line, it's ok ...

Also, could I have an example to change the color of the button according to the state of my lamp!

My requests may be silly, I apologize in advance.

Thank you

**Comment by Tom-Hirschberger** [comment]
Hi,

first of all: There are no silly questions.
The module is kept very simple and does not validate any return codes so it will not be possible to change the color.
It looks like your url contains characters which need to be escaped. Maybe you can try an online url encoder like  [https://meyerweb.com/eric/tools/dencoder/](https://meyerweb.com/eric/tools/dencoder/) to encode it and and the escaped string to the config.

Greets
Thomas

**Comment by Fabaude** [comment]
ok thanks for your quick response.
I will try your solution in a few days and tell you the rest.

Fab.

**Comment by Fabaude** [comment]
It does not work ...
On the command line: ~ $ curl "http: //xxx.xxx.x.xx: xxxx / json.htm? Type = command & param = switchlight & idx = xx & switchcmd = Toggle"  , it's good! Without  " " , not good. So how can I add  " "  to my config?
I hope to be clear.
Thank you

**Comment by Tom-Hirschberger** [comment]
Hi,

I think there will be two possible ways... Either remove all spaces from the part within the double quotes or alternatively put the string in single quotes and double quotes.
It may be helpful to use the absolute path of the curl command ("which curl" at the command line will find the location).

**Comment by Fabaude** [comment]
Well i will try your instructions. 
Thanks

**Comment by Fabaude** [comment]
Hello,
thank you so much,
with command: "curl" and url: '"http ..... On"' (put the string in single quotes and double quotes.) , it works perfectly!
I can now create switches for my Domoticz devices.
Great

Fab.

**Comment by Fabaude** [comment]
👍

**Comment by Tom-Hirschberger** [comment]
Hi and sorry, I am currently building my new home and forgot to answer. Currently there is no possibility to add an title or something more than the icon to the buttons. I do not think it's a great deal to add such a feature but really do not have much time to program. I also like the idea to validate the return codes.
Maybe I will have time to give it a try in the new year. I will add two feature requests so it won't be forgotten.

**Comment by Fabaude** [comment]
Hello,
I also built my house, and I know the work that it represents!
I didn't want to bother you for the module but just close the conversation (error on my part).
I managed to duplicate the module to have several buttons on my different pages and that's great!
Thank you again and good luck ...
Fab

**Comment by Tom-Hirschberger** [comment]
@Fabaude Hi, i do not know if you still use my module. I release a new version today which makes it possible to set different icons based on the output/return code of the called command. So it might be possible to change the icon based on the state of your lamp now

**Comment by Fabaude** [comment]
Hello, I still use your module and this new version is welcome!  I will try to understand the new config and adapt it to my MM... A big thank you.

PS: I hope you are well in your new home!
Fab

**Comment by Tom-Hirschberger** [comment]
Great to hear that you still use my module and thank you we live now in hour house. Still some small work to do but the main parts are ready. Cause of a torn ligament (happened during the last small work) i do have some time to code at the moment.

Your old configuration still should work without changes but with the new "conditions" you can change the icons or add classes (which can be used to change the color of the icon and things like that).

**Comment by Fabaude** [comment]
Hello, I did the update and I get a black screen when starting MM... I will look into more detail in the coming days.  Speedy recovery !

**Comment by Tom-Hirschberger** [comment]
Oh, not good.
Did you do the

```
npm installl
```


Dependencies changed with this version. Maybe a library is missing.

**Comment by Tom-Hirschberger** [comment]
Sorry, but i needed to a release a new version, again.

There was a bug which caused the module not to start if no additional classes had been set. Version 0.0.3 should work now.

**Comment by Fabaude** [comment]
Ok, I'll do an update tonight if the agenda allows me.  Thanks

**Comment by Fabaude** [comment]
hello, I'll admit that the update saves me!  I had tried to find my problem and the new version put everything back in place.  Thanks a lot.
